"""users table

Revision ID: 3beb1904fad6
Revises: 5f50b2014e5d
Create Date: 2021-06-14 00:33:39.825671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3beb1904fad6'
down_revision = '5f50b2014e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('title', sa.String(length=256), nullable=True))
    op.drop_column('story', 'titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('titles', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('story', 'title')
    # ### end Alembic commands ###
