"""stories table

Revision ID: 537662fb2c04
Revises: 3beb1904fad6
Create Date: 2021-06-14 01:55:26.523647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537662fb2c04'
down_revision = '3beb1904fad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('storyPicture', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'storyPicture')
    # ### end Alembic commands ###
