"""empty message

Revision ID: 6460c93ff5e6
Revises: bab4cebb05bd
Create Date: 2021-06-14 05:21:01.665926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6460c93ff5e6'
down_revision = 'bab4cebb05bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_location', table_name='user')
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.create_index('ix_user_location', 'user', ['location'], unique=False)
    # ### end Alembic commands ###
