"""users table

Revision ID: e993c064eade
Revises: 6659a9b2ce56
Create Date: 2021-06-13 21:17:37.240182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e993c064eade'
down_revision = '6659a9b2ce56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('titles', sa.String(length=256), nullable=True))
    op.add_column('story', sa.Column('body', sa.String(length=4096), nullable=True))
    op.drop_column('story', 'title')
    op.add_column('user', sa.Column('profilePicture_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilePicture_path')
    op.add_column('story', sa.Column('title', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('story', 'body')
    op.drop_column('story', 'titles')
    # ### end Alembic commands ###
